import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import QueryProviders from "@/state/query-client";
import { Toaster } from "@/components/ui/toaster";
import { ClientMiddleware } from "@/state/client-middleware";
import { headers } from "next/headers";
import { redirect } from "next/navigation";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Consumer",
  description: "Generated by selise blocks",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await headers();
  if (headersList.get("x-current-path") === "/activate-success") {
    redirect("/");
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProviders>
          <ClientMiddleware>{children}</ClientMiddleware>
        </QueryProviders>
        <Toaster />
      </body>
    </html>
  );
}
