import { TEmailData } from '../types/email.types';

export const emailData: TEmailData = {
  inbox: [
    {
      id: 'i1',
      sender: 'Adrian Müller',
      subject: 'Meeting Tomorrow',
      preview:
        '<p>Dear,</p><p>I hope this message finds you well. I am writing to follow up on the progress of [specific project/task] and to discuss the next steps. As per our last meeting, we aimed to achieve.</p><p><br></p><p>Could you please provide an update on the current status? Additionally, if there are any challenges or adjustments required, I would be happy to assist in addressing them.</p><p><br></p><p>Looking forward to your reply.</p><p><br></p><p>Best regards, Md</p>',
      date: '2025-03-23T09:31:25.000Z',
      isRead: false,
      hasAttachment: true,
      email: 'adrian.mueller@gmail.com',
      tags: {
        personal: true,
        work: true,
        payments: false,
        invoices: false,
      },
      bookmarked: true,
      trash: false,
      spam: false,
      isStarred: true,
      isImportant: true,
    },
    {
      id: 'i2',
      sender: 'Ethan Gold',
      subject: 'Meeting Rescheduled',
      preview:
        '<p>Dear,</p><p>I hope this message finds you well. I am writing to follow up on the progress of [specific project/task] and to discuss the next steps. As per our last meeting, we aimed to achieve.</p><p><br></p><p>Could you please provide an update on the current status? Additionally, if there are any challenges or adjustments required, I would be happy to assist in addressing them.</p><p><br></p><p>Looking forward to your reply.</p><p><br></p><p>Best regards, Md</p>',
      date: `2025-03-27T09:31:25.000Z`,
      isRead: false,
      isStarred: false,
      isImportant: false,
      hasAttachment: false,
      bookmarked: false,
      trash: false,
      spam: false,
      tags: {
        personal: true,
        work: true,
        payments: false,
        invoices: false,
      },
    },
    {
      id: 'i3',
      sender: 'Sophie Meier',
      subject: 'Reminder: Submit Your Report',
      preview:
        '<p>Dear,</p><p>I hope this message finds you well. I am writing to follow up on the progress of [specific project/task] and to discuss the next steps. As per our last meeting, we aimed to achieve.</p><p><br></p><p>Could you please provide an update on the current status? Additionally, if there are any challenges or adjustments required, I would be happy to assist in addressing them.</p><p><br></p><p>Looking forward to your reply.</p><p><br></p><p>Best regards, Md</p>',
      date: '2025-03-23T09:31:25.000Z',
      isRead: true,
      isStarred: true,
      isImportant: false,
      hasAttachment: false,
      bookmarked: false,
      trash: false,
      spam: false,
      tags: {
        personal: false,
        work: false,
        payments: false,
        invoices: false,
      },
    },
    {
      id: 'i4',
      sender: 'Adrian Müller',
      subject: 'Meeting Tomorrow',
      preview:
        '<p>Dear,</p><p>I hope this message finds you well. I am writing to follow up on the progress of [specific project/task] and to discuss the next steps. As per our last meeting, we aimed to achieve.</p><p><br></p><p>Could you please provide an update on the current status? Additionally, if there are any challenges or adjustments required, I would be happy to assist in addressing them.</p><p><br></p><p>Looking forward to your reply.</p><p><br></p><p>Best regards, Md</p>',
      date: '2025-03-23T09:31:25.000Z',
      isRead: false,
      isStarred: true,
      isImportant: true,
      hasAttachment: true,
      email: 'adrian.mueller@gmail.com',
      bookmarked: false,
      trash: false,
      spam: false,
      tags: {
        personal: true,
        work: false,
        payments: false,
        invoices: false,
      },
    },
    {
      id: 'i5',
      sender: 'Ethan Gold',
      subject: 'Meeting Rescheduled',
      preview:
        '<p>Dear,</p><p>I hope this message finds you well. I am writing to follow up on the progress of [specific project/task] and to discuss the next steps. As per our last meeting, we aimed to achieve.</p><p><br></p><p>Could you please provide an update on the current status? Additionally, if there are any challenges or adjustments required, I would be happy to assist in addressing them.</p><p><br></p><p>Looking forward to your reply.</p><p><br></p><p>Best regards, Md</p>',
      date: `2025-03-27T09:31:25.000Z`,
      isRead: false,
      isStarred: false,
      isImportant: false,
      hasAttachment: false,
      bookmarked: false,
      trash: false,
      spam: false,
      tags: {
        personal: false,
        work: true,
        payments: false,
        invoices: false,
      },
    },
    {
      id: 'i6',
      sender: 'Sophie Meier',
      subject: 'Reminder: Submit Your Report',
      preview:
        '<p>Dear,</p><p>I hope this message finds you well. I am writing to follow up on the progress of [specific project/task] and to discuss the next steps. As per our last meeting, we aimed to achieve.</p><p><br></p><p>Could you please provide an update on the current status? Additionally, if there are any challenges or adjustments required, I would be happy to assist in addressing them.</p><p><br></p><p>Looking forward to your reply.</p><p><br></p><p>Best regards, Md</p>',
      date: '2025-03-23T09:31:25.000Z',
      isRead: true,
      isStarred: true,
      isImportant: false,
      hasAttachment: false,
      bookmarked: false,
      trash: false,
      spam: false,
      tags: {
        personal: false,
        work: false,
        payments: false,
        invoices: false,
      },
    },
    {
      id: 'i7',
      sender: 'Adrian Müller',
      subject: 'Meeting Tomorrow',
      preview:
        '<p>Dear,</p><p>I hope this message finds you well. I am writing to follow up on the progress of [specific project/task] and to discuss the next steps. As per our last meeting, we aimed to achieve.</p><p><br></p><p>Could you please provide an update on the current status? Additionally, if there are any challenges or adjustments required, I would be happy to assist in addressing them.</p><p><br></p><p>Looking forward to your reply.</p><p><br></p><p>Best regards, Md</p>',
      date: '2025-03-23T09:31:25.000Z',
      isRead: false,
      isStarred: true,
      isImportant: true,
      hasAttachment: true,
      email: 'adrian.mueller@gmail.com',
      bookmarked: false,
      trash: false,
      spam: false,
      tags: {
        personal: false,
        work: false,
        payments: false,
        invoices: false,
      },
    },
    {
      id: 'i8',
      sender: 'Ethan Gold',
      subject: 'Meeting Rescheduled',
      preview:
        '<p>Dear,</p><p>I hope this message finds you well. I am writing to follow up on the progress of [specific project/task] and to discuss the next steps. As per our last meeting, we aimed to achieve.</p><p><br></p><p>Could you please provide an update on the current status? Additionally, if there are any challenges or adjustments required, I would be happy to assist in addressing them.</p><p><br></p><p>Looking forward to your reply.</p><p><br></p><p>Best regards, Md</p>',
      date: `2025-03-27T09:31:25.000Z`,
      isRead: false,
      isStarred: false,
      isImportant: false,
      hasAttachment: false,
      bookmarked: false,
      trash: false,
      spam: false,
      tags: {
        personal: false,
        work: false,
        payments: false,
        invoices: false,
      },
    },
    {
      id: 'i9',
      sender: 'Sophie Meier',
      subject: 'Reminder: Submit Your Report',
      preview:
        '<p>Dear,</p><p>I hope this message finds you well. I am writing to follow up on the progress of [specific project/task] and to discuss the next steps. As per our last meeting, we aimed to achieve.</p><p><br></p><p>Could you please provide an update on the current status? Additionally, if there are any challenges or adjustments required, I would be happy to assist in addressing them.</p><p><br></p><p>Looking forward to your reply.</p><p><br></p><p>Best regards, Md</p>',
      date: '2025-03-23T09:31:25.000Z',
      isRead: true,
      isStarred: true,
      isImportant: false,
      hasAttachment: false,
      bookmarked: false,
      trash: false,
      spam: false,
      tags: {
        personal: false,
        work: false,
        payments: false,
        invoices: false,
      },
    },
    {
      id: 'i10',
      sender: 'Adrian Müller',
      subject: 'Meeting Tomorrow',
      preview:
        '<p>Dear,</p><p>I hope this message finds you well. I am writing to follow up on the progress of [specific project/task] and to discuss the next steps. As per our last meeting, we aimed to achieve.</p><p><br></p><p>Could you please provide an update on the current status? Additionally, if there are any challenges or adjustments required, I would be happy to assist in addressing them.</p><p><br></p><p>Looking forward to your reply.</p><p><br></p><p>Best regards, Md</p>',
      date: '2025-03-23T09:31:25.000Z',
      isRead: false,
      isStarred: true,
      isImportant: true,
      hasAttachment: true,
      email: 'adrian.mueller@gmail.com',
      bookmarked: false,
      trash: false,
      spam: false,
      tags: {
        personal: false,
        work: false,
        payments: false,
        invoices: false,
      },
    },
    {
      id: 'i11',
      sender: 'Ethan Gold',
      subject: 'Meeting Rescheduled',
      preview:
        '<p>Dear,</p><p>I hope this message finds you well. I am writing to follow up on the progress of [specific project/task] and to discuss the next steps. As per our last meeting, we aimed to achieve.</p><p><br></p><p>Could you please provide an update on the current status? Additionally, if there are any challenges or adjustments required, I would be happy to assist in addressing them.</p><p><br></p><p>Looking forward to your reply.</p><p><br></p><p>Best regards, Md</p>',
      date: `2025-03-27T09:31:25.000Z`,
      isRead: false,
      isStarred: false,
      isImportant: false,
      hasAttachment: false,
      bookmarked: false,
      trash: false,
      spam: false,
      tags: {
        personal: false,
        work: false,
        payments: false,
        invoices: false,
      },
    },
    {
      id: 'i12',
      sender: 'Sophie Meier',
      subject: 'Reminder: Submit Your Report',
      preview:
        '<p>Dear,</p><p>I hope this message finds you well. I am writing to follow up on the progress of [specific project/task] and to discuss the next steps. As per our last meeting, we aimed to achieve.</p><p><br></p><p>Could you please provide an update on the current status? Additionally, if there are any challenges or adjustments required, I would be happy to assist in addressing them.</p><p><br></p><p>Looking forward to your reply.</p><p><br></p><p>Best regards, Md</p>',
      date: '2025-03-23T09:31:25.000Z',
      isRead: true,
      isStarred: true,
      isImportant: false,
      hasAttachment: false,
      bookmarked: false,
      trash: false,
      spam: false,
      tags: {
        personal: false,
        work: false,
        payments: false,
        invoices: false,
      },
    },
  ],
  starred: [
    {
      id: 's4',
      recipient: 'Jonathan Davis',
      subject: 'Meeting Agenda',
      preview:
        '<p>Dear,</p><p>I hope this message finds you well. I am writing to follow up on the progress of [specific project/task] and to discuss the next steps. As per our last meeting, we aimed to achieve.</p><p><br></p><p>Could you please provide an update on the current status? Additionally, if there are any challenges or adjustments required, I would be happy to assist in addressing them.</p><p><br></p><p>Looking forward to your reply.</p><p><br></p><p>Best regards, Md</p>',
      date: '2025-03-26T08:10:00.000Z',
      isRead: false,
      isStarred: false,
      isImportant: false,
      hasAttachment: false,
      bookmarked: false,
      trash: false,
      spam: false,
      tags: {
        personal: false,
        work: false,
        payments: false,
        invoices: false,
      },
    },
  ],
  important: [
    {
      id: 'im5',
      recipient: 'Jonathan Davis',
      subject: 'Meeting Agenda',
      preview:
        '<p>Dear,</p><p>I hope this message finds you well. I am writing to follow up on the progress of [specific project/task] and to discuss the next steps. As per our last meeting, we aimed to achieve.</p><p><br></p><p>Could you please provide an update on the current status? Additionally, if there are any challenges or adjustments required, I would be happy to assist in addressing them.</p><p><br></p><p>Looking forward to your reply.</p><p><br></p><p>Best regards, Md</p>',
      date: '2025-03-26T08:10:00.000Z',
      isRead: false,
      isStarred: false,
      isImportant: false,
      hasAttachment: false,
      bookmarked: false,
      trash: false,
      spam: false,
      tags: {
        personal: true,
        work: true,
        payments: false,
        invoices: false,
      },
    },
  ],
  sent: [
    {
      id: 'se4',
      recipient: 'Michael Brown',
      subject: 'Project Update',
      preview:
        '<p>Dear,</p><p>I hope this message finds you well. I am writing to follow up on the progress of [specific project/task] and to discuss the next steps. As per our last meeting, we aimed to achieve.</p><p><br></p><p>Could you please provide an update on the current status? Additionally, if there are any challenges or adjustments required, I would be happy to assist in addressing them.</p><p><br></p><p>Looking forward to your reply.</p><p><br></p><p>Best regards, Md</p>',
      date: '2025-03-24T14:15:00.000Z',
      isRead: true,
      isStarred: false,
      isImportant: false,
      hasAttachment: false,
      bookmarked: false,
      trash: false,
      spam: false,
      tags: {
        personal: true,
        work: true,
        payments: false,
        invoices: false,
      },
    },
    {
      id: 'se5',
      recipient: 'Emma Smith',
      subject: 'Invoice for March',
      preview:
        '<p>Dear,</p><p>I hope this message finds you well. I am writing to follow up on the progress of [specific project/task] and to discuss the next steps. As per our last meeting, we aimed to achieve.</p><p><br></p><p>Could you please provide an update on the current status? Additionally, if there are any challenges or adjustments required, I would be happy to assist in addressing them.</p><p><br></p><p>Looking forward to your reply.</p><p><br></p><p>Best regards, Md</p>',
      date: '2025-03-22T10:45:30.000Z',
      isRead: true,
      isStarred: false,
      isImportant: true,
      hasAttachment: true,
      bookmarked: false,
      trash: false,
      spam: false,
      tags: {
        personal: true,
        work: true,
        payments: false,
        invoices: false,
      },
    },
  ],
  drafts: [
    {
      id: 'd6',
      recipient: 'Jonathan Davis',
      subject: 'Meeting Agenda',
      preview:
        '<p>Dear,</p><p>I hope this message finds you well. I am writing to follow up on the progress of [specific project/task] and to discuss the next steps. As per our last meeting, we aimed to achieve.</p><p><br></p><p>Could you please provide an update on the current status? Additionally, if there are any challenges or adjustments required, I would be happy to assist in addressing them.</p><p><br></p><p>Looking forward to your reply.</p><p><br></p><p>Best regards, Md</p>',
      date: '2025-03-26T08:10:00.000Z',
      isRead: false,
      isStarred: false,
      isImportant: false,
      hasAttachment: false,
      bookmarked: false,
      trash: false,
      spam: false,
      tags: {
        personal: true,
        work: true,
        payments: false,
        invoices: false,
      },
    },
  ],
  spam: [
    {
      id: 'sp6',
      recipient: 'Jonathan Davis',
      subject: 'Meeting Agenda',
      preview:
        '<p>Dear,</p><p>I hope this message finds you well. I am writing to follow up on the progress of [specific project/task] and to discuss the next steps. As per our last meeting, we aimed to achieve.</p><p><br></p><p>Could you please provide an update on the current status? Additionally, if there are any challenges or adjustments required, I would be happy to assist in addressing them.</p><p><br></p><p>Looking forward to your reply.</p><p><br></p><p>Best regards, Md</p>',
      date: '2025-03-26T08:10:00.000Z',
      isRead: false,
      isStarred: false,
      isImportant: false,
      hasAttachment: false,
      bookmarked: false,
      trash: false,
      spam: false,
      tags: {
        personal: true,
        work: true,
        payments: false,
        invoices: false,
      },
    },
  ],
  trash: [],

  personal: [],
  work: [],
};

// export const emailData: TEmail[] = [
//   {
//     id: '1',
//     sender: 'Adrian Müller',
//     subject: 'Meeting Tomorrow',
//     preview:
//       "Hi, Let's have a meeting tomorrow to discuss the project. I've been reviewing the project details and have some ideas I'd like to share. It's crucial that we align on our next steps to ensure the project's success. Please come prepared with any questions or insights you may have. Looking forward to our meeting! Best regards, Adrian",
//     date: '2025-03-23T09:31:25.000Z',
//     isRead: false,
//     isStarred: true,
//     isImportant: true,
//     hasAttachment: true,
//     email: 'adrian.mueller@gmail.com',
//   },
//   {
//     id: '2',
//     sender: 'Ethan Gold',
//     subject: 'Meeting Rescheduled',
//     preview: 'Hey, The meeting originally scheduled for 2 PM has been moved to 3:30 PM. Let m...',
//     date: `2025-03-27T09:31:25.000Z`,
//     isRead: false,
//     isStarred: false,
//     isImportant: false,
//     hasAttachment: false,
//   },
//   {
//     id: '3',
//     sender: 'Sophie Meier',
//     subject: 'Reminder: Submit Your Report',
//     preview:
//       'Hello, Just a friendly reminder to submit your report by EOD today. Let us know if...',
//     date: '2025-03-23T09:31:25.000Z',
//     isRead: false,
//     isStarred: true,
//     isImportant: false,
//     hasAttachment: false,
//   },
//   {
//     id: '4',
//     sender: 'Luca Fischer',
//     subject: 'Subject: Lunch Plans?',
//     preview: 'Hey, Are we still on for lunch tomorrow? Let me know what time works for you!...',
//     date: '2025-03-23T09:31:25.000Z',
//     isRead: true,
//     isStarred: false,
//     isImportant: true,
//     hasAttachment: false,
//   },
//   {
//     id: '5',
//     sender: 'Julian Schmid',
//     subject: 'Quick Question',
//     preview: "Hey, Do you have the latest version of the project doc? I can't seem to find it...",
//     date: '2025-03-23T09:31:25.000Z',
//     isRead: true,
//     isStarred: false,
//     isImportant: false,
//     hasAttachment: true,
//   },
//   {
//     id: '6',
//     sender: 'Lena Weber',
//     subject: 'Project Update',
//     preview: 'Hi, Here’s the latest update on the project. We’ve made significant progress...',
//     date: '2025-03-23T09:31:25.000Z',
//     isRead: true,
//     isStarred: false,
//     isImportant: false,
//     hasAttachment: false,
//   },
//   {
//     id: '7',
//     sender: 'Noah Becker',
//     subject: 'Feedback Needed',
//     preview: 'Hello, Could you please review the attached document and provide your feedback...',
//     date: '2025-03-23T09:31:25.000Z',
//     isRead: true,
//     isStarred: false,
//     isImportant: false,
//     hasAttachment: true,
//   },
//   {
//     id: '8',
//     sender: 'Mia Hoffmann',
//     subject: 'Team Meeting Agenda',
//     preview: 'Hey, Here’s the agenda for our team meeting tomorrow. Please review it before...',
//     date: '2025-03-23T09:31:25.000Z',
//     isRead: true,
//     isStarred: true,
//     isImportant: false,
//     hasAttachment: false,
//   },
//   {
//     id: '9',
//     sender: 'Elias Richter',
//     subject: 'New Feature Announcement',
//     preview: 'Hi Team, We’re excited to announce the launch of a new feature. Check it out...',
//     date: '2025-03-23T09:31:25.000Z',
//     isRead: true,
//     isStarred: false,
//     isImportant: true,
//     hasAttachment: false,
//   },
//   {
//     id: '10',
//     sender: 'Clara Schulz',
//     subject: 'Holiday Party Details',
//     preview: 'Hello, Here are the details for our upcoming holiday party. Looking forward to...',
//     date: '2025-03-23T09:31:25.000Z',
//     isRead: true,
//     isStarred: false,
//     isImportant: false,
//     hasAttachment: false,
//   },
//   {
//     id: '11',
//     sender: 'David Wolf',
//     subject: 'Client Meeting Notes',
//     preview: 'Hi, Attached are the notes from our client meeting. Please review and let me...',
//     date: '2025-03-23T09:31:25.000Z',
//     isRead: true,
//     isStarred: false,
//     isImportant: false,
//     hasAttachment: true,
//   },
//   {
//     id: '12',
//     sender: 'Anna Braun',
//     subject: 'Project Deadline Reminder',
//     preview: 'Hello, Just a reminder that the project deadline is approaching. Please ensure...',
//     date: '2025-03-23T09:31:25.000Z',
//     isRead: true,
//     isStarred: false,
//     isImportant: false,
//     hasAttachment: false,
//   },
//   {
//     id: '13',
//     sender: 'Paul König',
//     subject: 'Training Session Feedback',
//     preview: 'Hey, Thank you for attending the training session. Your feedback is appreciated...',
//     date: '2025-03-23T09:31:25.000Z',
//     isRead: true,
//     isStarred: true,
//     isImportant: false,
//     hasAttachment: false,
//   },
//   {
//     id: '14',
//     sender: 'Laura Gross',
//     subject: 'Team Outing Plans',
//     preview: 'Hi, We’re planning a team outing next month. Any suggestions on where to go?...',
//     date: '2025-03-23T09:31:25.000Z',
//     isRead: true,
//     isStarred: false,
//     isImportant: true,
//     hasAttachment: false,
//   },
//   {
//     id: '15',
//     sender: 'Simon Jung',
//     subject: 'New Policy Announcement',
//     preview: 'Hello, We’re introducing a new company policy effective next week. Please read...',
//     date: '2025-03-23T09:31:25.000Z',
//     isRead: true,
//     isStarred: false,
//     isImportant: false,
//     hasAttachment: false,
//   },
//   {
//     id: '16',
//     sender: 'Hannah Keller',
//     subject: 'Sales Report',
//     preview: 'Hi, Attached is the monthly sales report. Please review it and let me know if...',
//     date: '2025-03-23T09:31:25.000Z',
//     isRead: true,
//     isStarred: false,
//     isImportant: false,
//     hasAttachment: true,
//   },
//   {
//     id: '17',
//     sender: 'Maximilian Vogel',
//     subject: 'Project Proposal Review',
//     preview: 'Hello, Could you please review the attached project proposal and provide your...',
//     date: '2025-03-23T09:31:25.000Z',
//     isRead: true,
//     isStarred: false,
//     isImportant: false,
//     hasAttachment: false,
//   },
//   {
//     id: '18',
//     sender: 'Lea Hartmann',
//     subject: 'Website Maintenance',
//     preview: 'Hey, We’ll be performing website maintenance this weekend. Please be aware of...',
//     date: '2025-03-23T09:31:25.000Z',
//     isRead: true,
//     isStarred: true,
//     isImportant: false,
//     hasAttachment: false,
//   },
//   {
//     id: '19',
//     sender: 'Felix Lange',
//     subject: 'Customer Feedback',
//     preview: 'Hi, We’ve received some positive customer feedback. Check out the attached...',
//     date: '2025-03-23T09:31:25.000Z',
//     isRead: true,
//     isStarred: false,
//     isImportant: true,
//     hasAttachment: false,
//   },
//   {
//     id: '20',
//     sender: 'Emilia Wagner',
//     subject: 'Office Closure Notice',
//     preview: 'Hello, Please be informed that the office will be closed on [Date] for [Reason]...',
//     date: '2025-03-23T09:31:25.000Z',
//     isRead: true,
//     isStarred: false,
//     isImportant: false,
//     hasAttachment: false,
//   },
//   {
//     id: '21',
//     sender: 'Lea Hartmann',
//     subject: 'Website Maintenance',
//     preview: 'Hey, We’ll be performing website maintenance this weekend. Please be aware of...',
//     date: '2025-03-23T09:31:25.000Z',
//     isRead: true,
//     isStarred: true,
//     isImportant: false,
//     hasAttachment: false,
//   },
//   {
//     id: '22',
//     sender: 'Felix Lange',
//     subject: 'Customer Feedback',
//     preview: 'Hi, We’ve received some positive customer feedback. Check out the attached...',
//     date: '2025-03-23T09:31:25.000Z',
//     isRead: true,
//     isStarred: false,
//     isImportant: true,
//     hasAttachment: false,
//   },
//   {
//     id: '23',
//     sender: 'Emilia Wagner',
//     subject: 'Office Closure Notice',
//     preview: 'Hello, Please be informed that the office will be closed on [Date] for [Reason]...',
//     date: '2025-03-23T09:31:25.000Z',
//     isRead: true,
//     isStarred: false,
//     isImportant: false,
//     hasAttachment: false,
//   },
// ];
